export { default as About } from "./About";
export { default as Categories } from "./Categories";
export { default as Category } from "./Category";
export { default as Confirmation } from "./Confirmation";
export { default as Header } from "./Header";
export { default as Home } from "./Home";
export { default as NotFound } from "./NotFound";
export { default as Register } from "./Register";
export { default as Session } from "./Session";
